### ISSUE TITLE
would paho work in 8266?

### ISSUE THREAD

**Issue by pandysong** [soynerdito/ESP8266-MQTT#1]
See following 
http://www.eclipse.org/paho/clients/c/embedded-sn/
Not sure it will meet your requirement.

Anyhow it is an interesting project.

**Comment by soynerdito** [comment]
Yes, that exactly is the idea. I used a CC3000 with a Paho implementation. It is implemented on a library found online PubSubClient. It worked pretty good here is the code (https://github.com/soynerdito/SkullIOT/blob/master/Arduino/Skullmqtt_basic.ino).
What I want to do is write a class that extends from Client (like the ethernet client for arduino). If I can do that then in theory that PubSubClient library that uses mqtt should work for my Arduino projects. And maybe other ethernet arduino code can be used as well (who knows). But my main goal is to work with PubSucClient library. All this is very early, and may work or may not but I have to give it a try.

**Comment by soynerdito** [comment]
Today I just saw that the official AT firmware for the ESP8266 has MQTT in the future path. This project might not be needed at all (or modified greatly).
Check link: https://github.com/atdeveloper/atproto
